apiVersion: batch/v1
kind: Job
metadata:
  name: demo-job
  namespace: nginx  # Ensure this namespace exists
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      name: demo-job-pod
      labels:
        app: batch-task
    spec:       # <-- move this spec here, under template, not under metadata
      containers:
        - name: batch-container
          image: busybox:latest
          command: ["sh", "-c", "echo Hello Dosto! && sleep 10"]
      restartPolicy: Never

